### ISSUE TITLE
Implement GetPixelCountFromFile

### ISSUE THREAD

**Issue by TessFerrandez** [TessFerrandez/QSEC_ImageFramework#2]
Given a file name, method should return the number of pixels that make up the image

**Acceptance criteria:**
- No filename - Throws ArgumentNullException
- Image file - Returns number of pixels
- Not an image file - Throws InvalidOperationException

Should accept png and jpg including semitransparent png (with alpha channel)

This should be implemented in the ImageInfo Class

**Comment by TessFerrandez** [comment]
Suggested Coding Music : Papauotai https://open.spotify.com/track/34dx8DACTJsc3rsJdaEIQw?si=W8oV12O8S3mz81Ll69msIw

**Comment by buzzfrog** [comment]
I'll do it

**Comment by TessFerrandez** [comment]
💯
