### ISSUE TITLE
Implement Resize

### ISSUE THREAD

**Issue by TessFerrandez** [TessFerrandez/QSEC_ImageFramework#5]
Image Resize(Image image, int newHeight, int newWidth) 

Resize an image to a new given height and width. 
It is ok if the resize squishes the image

Acceptance criteria:

New size = 0 - Throw ArgumentOutOfRangeException
Image  - Throws ArgumentNullException
Image - new image should have the right format

This should be implemented in the ImageInfo Class

**Comment by syedhassaanahmed** [comment]
I'll attempt this one
